#!/bin/bash

echo "Starting RouteurServices..."


ip link set dev eth0 up
ip addr add 8.27.4.50/28 dev eth0
ip link set dev eth1 up
ip addr add 8.27.4.81/28 dev eth1
ip link set dev eth2 up
ip addr add 8.27.4.97/28 dev eth2

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start