#!/bin/bash

echo "Starting R1..."


ip link set dev eth0 up
ip addr add 8.27.4.34/28 dev eth0
ip link set dev eth1 up
ip addr add 8.27.4.49/28 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

service quagga start