#!/bin/bash
ip link set dev eth0 up
ip link set dev eth1 up
ip addr add 31.5.253.18/28 dev eth0
ip addr add 192.168.91.129/26 dev eth1

# la connexion avec le FAI -> route par defaut
ip route add default via 31.5.253.17

# DHCP
service isc-dhcp-server start

# Protéger le réseau privé
iptables -t nat -A POSTROUTING -s 192.168.91.128/26 -j MASQUERADE

# Refuser toutes les operations
iptables -P INPUT DROP
iptables -P OUTPUT DROP
iptables -P FORWARD DROP

# Autoriser les pings
iptables -t filter -A INPUT -p icmp -j ACCEPT
iptables -t filter -A OUTPUT -p icmp -j ACCEPT
iptables -t filter -A FORWARD -p icmp -j ACCEPT

# Autoriser le protocole RIP
iptables -A INPUT -p udp --dport 520 -j ACCEPT
iptables -A OUTPUT -p udp --dport 520 -j ACCEPT
iptables -A FORWARD -p udp --dport 520 -j ACCEPT

# Autoriser le service DNS
iptables -t filter -A FORWARD -d 31.5.253.226/27 -p udp --dport 53 -j ACCEPT
iptables -t filter -A FORWARD -s 31.5.253.226/27 -p udp --sport 53 -j ACCEPT

#Autoriser le web
iptables -t filter -A FORWARD -p tcp --dport 80 -j ACCEPT
iptables -t filter -A FORWARD -p tcp --sport 80 -j ACCEPT
