#!/bin/bash

echo "Starting Box1..."


ip link set dev eth0 up
ip addr add 192.168.147.129/25 dev eth0
ip link set dev eth1 up
ip addr add 8.27.4.1/28 dev eth1

echo 1 > /proc/sys/net/ipv4/ip_forward

service isc-dhcp-server start
dhclient -nw ethX